### PR TITLE
fix: Fix some deprecation warnings

### PR DESCRIPTION
**Pull request by jagged3dge**
Fixes applied in accordance to Atom 1.0 standards:
Changed styles folder naming.
Replaced some selectors.
Does not handle shadowDOM yet.

### CODE REVIEW

**Comment by keeev** [comment]
Hey @jagged3dge thx for the PR and for updating the theme. :+1: :tada: 

On my machine the theme appears white and without some styling all over the ui. 
How's it about you?

**Comment by jagged3dge** [comment]
Hm. It's looking alright on my end. Would you mind posting a screenshot of how it looks for you?

**Comment by keeev** [comment]
Sure: 

screen shot 2015-07-20 at 19 53 13

And some code, or better the index.less with all it's imports

screen shot 2015-07-20 at 19 53 06

**Comment by jagged3dge** [comment]
That's definitely wierd. This is how it looks on my screen:
image

And the same index.less file:
image

**Comment by keeev** [comment]
Thx, I'll check this out asap and let you know what the problem was.

**Comment by keeev** [comment]
That's weird, it still doesn't work. Even though I downloaded your master via .zip and before via git. Some changes didn't change with merging your changes into my master which was up to date. I compared them with our diffs in the "Files changed" tab here above. Mhm ...

**Comment by jagged3dge** [comment]
Not sure why that's happening. Maybe this was a bad idea :P Closing this PR.

**Pull request closed without merging**
